swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  code_version_result:
    description: Result document containing an array of code versions.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        description: The array of code versions
        items:
          $ref: '#/definitions/code_version'
        type: array
      next:
        description: The URL of the next result page.
        type: string
      previous:
        description: The URL of the previous result page.
        type: string
      select:
        description: The fields that you want to select.
        type: string
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  code_version:
    description: Document representing a code version
    properties:
      activation_time:
        description: The code version activation time.
        format: date-time
        type: string
      active:
        description: Use this method to determine, if this code version is currently
          active.
        type: boolean
      cartridges:
        description: A list containing the names of all cartridges participating in
          this code version.
        items:
          type: string
        type: array
      compatibility_mode:
        description: The code version compatibility mode.
        type: string
      id:
        description: The code version id.
        type: string
      last_modification_time:
        description: The last time, when the code version was changed.
        format: date-time
        type: string
      rollback:
        description: Use this method to determine, if this code version is the current
          rollback version.
        type: boolean
      total_size:
        description: Returns the total size of the file system content of this code
          version in bytes.
        format: int64
        type: integer
      web_dav_url:
        description: Returns the HTTPS based WebDAV URL that can be used to access
          the code version resources.
        type: string
paths:
  /code_versions:
    get:
      description: Read all existing code versions.
      operationId: getCodeVersions
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/code_version_result'
      security:
      - oauth2_application: []
      tags:
      - code_versions
