swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  customer:
    description: Document representing a customer.
    properties:
      birthday:
        description: The customer's birthday.
        format: date
        x-label:
          default: Birthday
        type: string
      c_familyStatus:
        x-label:
          default: Family Status
        type: string
      c_location:
        description: The shopper's specified location.
        format: text
        x-label:
          default: The shopper's specified location.
        type: string
      company_name:
        description: The customer's company name.
        x-label:
          default: Company
        maxLength: 256
        type: string
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      credentials:
        $ref: '#/definitions/credentials'
        description: The customer's credentials.
      customer_id:
        description: "The customer's id. Both registered and guest customers have\
          \ a\n customer id."
        maxLength: 28
        type: string
      customer_no:
        description: The customer's number.
        x-label:
          default: Customer No.
        maxLength: 100
        type: string
      email:
        description: The customer's email address.
        format: email
        x-label:
          default: Email
        maxLength: 256
        type: string
      fax:
        description: "The fax number to use for the customer.\n The length is restricted\
          \ to 32 characters."
        x-label:
          default: Fax Number
        maxLength: 32
        type: string
      first_name:
        description: The customer's first name.
        x-label:
          default: First Name
        maxLength: 256
        type: string
      gender:
        description: The customer's gender.
        enum:
        - 1
        - 2
        x-enum-labels:
        - default: Male
        - default: Female
        format: int32
        x-label:
          default: Gender
        type: integer
      global_party_id:
        description: The Global Party ID is set by Customer 360 and identifies a person
          across multiple systems.
        type: string
      job_title:
        description: The customer's job title.
        x-label:
          default: Job Title
        maxLength: 256
        type: string
      last_login_time:
        description: The last login time of the customer.
        format: date-time
        x-label:
          default: Last Login Time
        readOnly: true
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      last_name:
        description: The customer's last name.
        x-label:
          default: Last Name
        maxLength: 256
        type: string
      last_visit_time:
        description: The last visit time of the customer.
        format: date-time
        x-label:
          default: Last Visit Time
        readOnly: true
        type: string
      phone_business:
        description: The customer's business phone number.
        x-label:
          default: Business Phone
        maxLength: 32
        type: string
      phone_home:
        description: The customer's home phone number.
        x-label:
          default: Home Phone
        maxLength: 32
        type: string
      phone_mobile:
        description: The customer's mobile phone number.
        x-label:
          default: Mobile Phone
        maxLength: 32
        type: string
      preferred_locale:
        description: "The customer's preferred locale, formatted with a hyphen. (For\
          \ example: en-US)\n If the request uses an underscore, as with the Java\
          \ locale format, the stored value is converted to a hyphen.\n (For example:\
          \ en_US is stored as en-US)"
        x-label:
          default: Preferred Locale
        readOnly: true
        type: string
      previous_login_time:
        description: The time when the customer logged in previously.
        format: date-time
        type: string
      previous_visit_time:
        description: The time when the customer previously visited the store.
        format: date-time
        type: string
      primary_address:
        $ref: '#/definitions/customer_address'
        description: The customers primary or default address.
      salutation:
        description: The customer's salutation.
        x-label:
          default: Salutation
        maxLength: 256
        type: string
      second_name:
        description: The customer's second name.
        x-label:
          default: Second Name
        maxLength: 256
        type: string
      suffix:
        description: The customer's suffix (for example, "Jr." or "Sr.").
        x-label:
          default: Name Suffix
        maxLength: 256
        type: string
      title:
        description: The customer's title (for example, "Mrs" or "Mr").
        x-label:
          default: Title
        maxLength: 256
        type: string
  customer_search_result:
    description: Document representing a customer search result.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        items:
          type: object
        type: array
      db_start_record_:
        format: int32
        minimum: 0
        type: integer
      expand:
        description: The list of expands set. Can be empty.
        items:
          type: string
        type: array
      hits:
        description: The sorted array of search hits. Can be empty.
        items:
          $ref: '#/definitions/customer_search_hit'
        type: array
      next:
        $ref: '#/definitions/result_page'
        description: The URL of the next result page.
      previous:
        $ref: '#/definitions/result_page'
        description: The URL of the previous result page.
      query:
        $ref: '#/definitions/query'
        description: The requested query string.
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The fields that you want to select.
        type: string
      sorts:
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  credentials:
    description: Document representing the credentials of a customer.
    properties:
      enabled:
        description: A flag indicating whether the customer is enabled and can log.
        type: boolean
      locked:
        description: A flag indicating whether the customer account is locked.
        type: boolean
      login:
        description: The login of the customer.
        maxLength: 256
        type: string
      password_question:
        description: The password question.
        maxLength: 256
        type: string
    required:
    - login
  result_page:
    description: Data that can be used to get the next and previous page of a Data
      API results object.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        type: integer
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        type: integer
  query:
    description: "Document representing a query. A query contains a set of objects\
      \ that define criteria\n used to select records. A query can contain one of\
      \ the following:\n"
  customer_address:
    description: Document representing a customer address.
    properties:
      address1:
        description: The customer's first address.
        x-label:
          default: Address 1
        maxLength: 256
        type: string
      address2:
        description: The customer's second address value.
        x-label:
          default: Address 2
        maxLength: 256
        type: string
      address_id:
        description: The customer address id.
        x-label:
          default: Address ID
        maxLength: 256
        type: string
      city:
        description: The customer's city.
        x-label:
          default: City
        maxLength: 256
        type: string
      company_name:
        description: The customer's company name.
        x-label:
          default: Company
        maxLength: 256
        type: string
      country_code:
        description: The customer's two-character country code per ISO 3166-1 alpha-2.
        enum:
        - CN
        - FR
        - GB
        - IT
        - JP
        - US
        x-enum-labels:
        - default: China
        - default: France
        - default: United Kingdom
        - default: Italy
        - default: Japan
        - default: United States
        x-label:
          default: Country
        maxLength: 2
        type: string
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      etag:
        description: The generated eTag representing the state of the customer address.
        type: string
      first_name:
        description: The customer's first name.
        x-label:
          default: First Name
        maxLength: 256
        type: string
      full_name:
        description: The concatenation of the customer's first, middle, and last names
          and its suffix.
        type: string
      job_title:
        description: The customer's job title.
        x-label:
          default: Job Title
        maxLength: 256
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      last_name:
        description: The customer's last name.
        x-label:
          default: Last Name
        maxLength: 256
        type: string
      phone:
        description: The customer's phone number.
        x-label:
          default: Contact Phone
        maxLength: 32
        type: string
      post_box:
        description: The customer's post box.
        x-label:
          default: Post Box
        maxLength: 256
        type: string
      postal_code:
        description: The customer's postal code.
        x-label:
          default: Postal Code
        maxLength: 256
        type: string
      salutation:
        description: The customer's salutation.
        x-label:
          default: Salutation
        maxLength: 256
        type: string
      second_name:
        description: The customer's second name.
        x-label:
          default: Second Name
        maxLength: 256
        type: string
      state_code:
        description: The customer's state.
        x-label:
          default: State
        maxLength: 256
        type: string
      suffix:
        description: The customer's suffix.
        x-label:
          default: Suffix
        maxLength: 256
        type: string
      suite:
        description: The customer's suite.
        x-label:
          default: Suite No.
        maxLength: 32
        type: string
      title:
        description: The customer's title.
        x-label:
          default: Title
        maxLength: 256
        type: string
    required:
    - address_id
    - country_code
    - last_name
  search_request:
    description: Document representing a search request for retrieving items within
      the Data API. The query is a potentially complex set of expressions. The fields
      that each query supports are defined within the search resource.
    properties:
      count:
        description: The number of returned documents
        format: int32
        maximum: 200
        minimum: 1
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        minimum: 0
        type: integer
      expand:
        description: List of expansions to be applied to each search results. Expands
          are optional
        items:
          type: string
        type: array
      query:
        $ref: '#/definitions/query'
        description: The query to apply
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The field to be selected.
        type: string
      sorts:
        description: The list of sort clauses configured for the search request. Sort
          clauses are optional.
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
    required:
    - query
  customer_search_hit:
    description: Document representing a customer search hit.
    properties:
      data:
        $ref: '#/definitions/customer'
        description: ''
      relevance:
        description: The hit's relevance score.
        format: double
        type: number
  sort:
    description: Document representing a sort request.
    properties:
      field:
        description: The name of the field to sort on.
        type: string
      sort_order:
        description: The sort order to be applied when sorting. When omitted, the
          default sort order (ASC) is used.
        enum:
        - asc
        - desc
        type: string
    required:
    - field
paths:
  /customer_lists/{customer_list_id}/customer_search:
    post:
      description: "Action to search for customers in a customer list.\n\n The query\
        \ attribute specifies a complex query that can be used to narrow down the\
        \ search.\n Note that a text_query search only returns exact word matches.\
        \ For example, the search \n term \"Jon\" returns \"Jon Smith\", but doesn't\
        \ return \"Jonathan Smith\".\n \n These attributes are searchable:\n\n \n\
        \ - customer_no - String\n - first_name - String\n - second_name - String\n\
        \ - last_name - String\n - suffix - String\n - salutation - String\n - title\
        \ - String\n - fax - String\n - phone_home - String\n - phone_business - String\n\
        \ - phone_mobile - String\n - email - String\n - gender - Integer\n - company_name\
        \ - String\n - credentials.login - String\n - credentials.enabled - boolean\n\
        \ "
      operationId: postCustomerListsByIDCustomerSearch
      parameters:
      - description: The customer list id to search in
        in: path
        maxLength: 256
        minLength: 1
        name: customer_list_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/search_request'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/customer_search_result'
      security:
      - oauth2_application: []
      tags:
      - customer_lists
