swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions: {}
paths:
  /custom_object_definitions/{object_type}/attribute_groups/{group_id}/attribute_definitions/{def_id}:
    delete:
      description: Un-assign an attribute definition from an attribute group.
      operationId: deleteCustomObjectDefinitionsByIDAttributeGroupsByIDAttributeDefinitionsByID
      parameters:
      - description: The ID of the custom object that contains the attribute definition
          and attribute group.
        in: path
        name: object_type
        required: true
        type: string
      - description: The ID of the attribute group.
        in: path
        minLength: 1
        name: group_id
        required: true
        type: string
      - description: The ID of the attribute definition.
        in: path
        minLength: 1
        name: def_id
        required: true
        type: string
      responses:
        '204':
          description: ''
        '404':
          description: '`ObjectTypeNotFoundException` - Indicates the specified custom
            object is not found. or `AttributeGroupNotFoundException` - Indicates
            the specified attribute group is not found. or `AttributeDefinitionNotFoundException`
            - Indicates the specified attribute definition is not found.'
      security:
      - oauth2_application: []
      tags:
      - custom_object_definitions
    put:
      description: Assign an attribute definition to an attribute group.
      operationId: putCustomObjectDefinitionsByIDAttributeGroupsByIDAttributeDefinitionsByID
      parameters:
      - description: The ID of the custom object that contains the attribute definition
          and attribute group.
        in: path
        name: object_type
        required: true
        type: string
      - description: The ID of the attribute group.
        in: path
        minLength: 1
        name: group_id
        required: true
        type: string
      - description: The ID of the attribute definition.
        in: path
        minLength: 1
        name: def_id
        required: true
        type: string
      responses:
        '204':
          description: ''
        '404':
          description: '`ObjectTypeNotFoundException` - Indicates the specified custom
            object is not found. or `AttributeGroupNotFoundException` - Indicates
            the specified attribute group is not found. or `AttributeDefinitionNotFoundException`
            - Indicates the specified attribute definition is not found.'
      security:
      - oauth2_application: []
      tags:
      - custom_object_definitions
