swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  media_file:
    properties:
      abs_url:
        description: The absolute URL with request protocol (read only)
        type: string
      alt:
        additionalProperties:
          type: string
        description: The alternative image text
        format: localized
        type: object
      dis_base_url:
        description: The DIS base URL only for product images
        type: string
      path:
        description: "The raw media file path\n (only this needs to be provided in\
          \ update request)"
        type: string
      title:
        additionalProperties:
          type: string
        description: The image title
        format: localized
        type: object
  content_sub_folder_result:
    description: Result document containing an array of content subfolders.
    properties:
      count:
        description: The number of search results in the current page.
        format: int32
        type: integer
      data:
        description: The returned objects.
        items:
          type: object
        type: array
      hits:
        description: The sorted array of search hits. This array can be empty.
        items:
          $ref: '#/definitions/content_folder'
        type: array
      next:
        description: The URL of the next result page.
        type: string
      previous:
        description: The URL of the previous result page.
        type: string
      select:
        description: The fields that you want to select.
        type: string
      start:
        description: The zero-based index of the first search result to include in
          the document.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of search results.
        format: int32
        type: integer
  content_folder:
    description: Document representing a content folder.
    properties:
      c_customCSSFile:
        $ref: '#/definitions/media_file'
        description: Use this attribute to apply custom styles for this category.
        x-label:
          default: Custom CSS File
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      description:
        additionalProperties:
          type: string
        description: The localized content folder description.
        format: localized
        x-label:
          default: Description
        type: object
      id:
        description: The id of the content folder.
        x-label:
          default: ID
        maxLength: 256
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: The link to the content folder resource.
        type: string
      name:
        additionalProperties:
          type: string
        description: The localized content folder name.
        format: localized
        x-label:
          default: Name
        type: object
      online:
        description: A flag indicating whether the folder in online (default is false).
        x-label:
          default: Online
        type: boolean
      page_description:
        additionalProperties:
          type: string
        description: The localized content folder page description.
        format: localized
        x-label:
          default: Page Description
        type: object
      page_keywords:
        additionalProperties:
          type: string
        description: The localized content folder page keywords.
        format: localized
        x-label:
          default: Page Keywords
        type: object
      page_title:
        additionalProperties:
          type: string
        description: The localized content folder page title.
        format: localized
        x-label:
          default: Page Title
        type: object
      page_url:
        additionalProperties:
          type: string
        description: The localized content folder page URL.
        format: localized
        x-label:
          default: Page URL
        type: object
      parent_folder_id:
        description: The id of the parent content folder.
        type: string
      parent_link:
        description: The URL to the parent content folder.
        type: string
      sub_folders_link:
        description: The URL to list the content sub-folders.
        type: string
      template:
        description: The rendering template.
        x-label:
          default: Rendering Template
        type: string
paths:
  /libraries/{library_id}/folders/{folder_id}/sub_folders:
    get:
      description: Action to get sub folders information.
      operationId: getLibrariesByIDFoldersByIDSubFolders
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: ID of a target folder.
        in: path
        maxLength: 256
        minLength: 1
        name: folder_id
        required: true
        type: string
      - description: The result set index to return the first instance for. Default
          value is 0.
        format: int32
        in: query
        minimum: 0
        name: start
        type: integer
      - description: The maximum number of instances per request. Default value is
          25.
        format: int32
        in: query
        maximum: 200
        minimum: 1
        name: count
        type: integer
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_sub_folder_result'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `FolderNotFoundException` - Indicates that the
            folder with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
