swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  content_asset:
    description: Document representing a content asset.
    properties:
      c_Year:
        x-label:
          default: Year
        type: string
      c_body:
        additionalProperties:
          $ref: '#/definitions/markup_text'
        format: localized
        x-label:
          default: Body
        type: object
      c_customCSSFile:
        $ref: '#/definitions/media_file'
        description: Use this attribute to apply custom styles for this content asset.
        x-label:
          default: Custom CSS File
      classification_folder_id:
        description: The ID of the classification folder. It is only part of the response,
          if the assignment from  this content asset to the folder is marked as 'default'.
          The property is read-only. To  set the classification folder just create/update
          an assignment between this content asset and  a folder and mark it as 'default'.
          See details in  /libraries/{library_id}/folder_assignments/{content_id}/{folder_id}
          resource.
        type: string
      classification_folder_link:
        description: The link to the classification folder. It is only part of the
          response, if the assignment from  this content asset to the folder is marked
          as 'default'. The property is read-only. To  set the classification folder
          just create/update an assignment between this content asset and  a folder
          and mark it as 'default'. See details in  /libraries/{library_id}/folder_assignments/{content_id}/{folder_id}
          resource.
        type: string
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      description:
        additionalProperties:
          type: string
        description: The localized content asset description.
        format: localized
        x-label:
          default: Description
        type: object
      id:
        description: The id of the content asset.
        x-label:
          default: ID
        maxLength: 256
        minLength: 1
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: The link to the content asset resource.
        type: string
      name:
        additionalProperties:
          type: string
        description: The localized content asset name.
        format: localized
        x-label:
          default: Name
        type: object
      online:
        additionalProperties:
          type: boolean
        description: Is the asset online?
        format: site-specific
        x-label:
          default: Online
        type: object
      page_description:
        additionalProperties:
          type: string
        description: The localized content asset page description.
        format: localized
        x-label:
          default: Page Description
        type: object
      page_keywords:
        additionalProperties:
          type: string
        description: The localized content asset page keywords.
        format: localized
        x-label:
          default: Page Keywords
        type: object
      page_title:
        additionalProperties:
          type: string
        description: The localized content asset page title.
        format: localized
        x-label:
          default: Page Title
        type: object
      page_url:
        additionalProperties:
          type: string
        description: The localized content asset page url.
        format: localized
        x-label:
          default: Page URL
        type: object
      searchable:
        additionalProperties:
          type: boolean
        description: Is the asset searchable?
        format: site-specific
        type: object
      site_map_change_frequency:
        additionalProperties:
          enum:
          - always
          - daily
          - hourly
          - monthly
          - never
          - weekly
          - yearly
          x-enum-labels:
          - default: always
          - default: daily
          - default: hourly
          - default: monthly
          - default: never
          - default: weekly
          - default: yearly
          type: string
        description: The content assets change frequency needed for the sitemap creation  (always,
          hourly, daily, weekly, monthly, yearly, never).
        format: site-specific
        x-label:
          default: Change Frequency
        type: object
      site_map_included:
        additionalProperties:
          enum:
          - 0
          - 1
          x-enum-labels:
          - default: 'NO'
          - default: 'YES'
          format: int32
          maximum: 1
          minimum: 0
          type: integer
        description: The status if the content asset is included into the sitemap
          (either 0 or  1).
        format: site-specific
        x-label:
          default: Included
        type: object
      site_map_priority:
        additionalProperties:
          format: double
          maximum: 1
          type: number
        description: The content assets priority needed for the sitemap creation (0.0
          for no  priority defined).
        format: site-specific
        x-label:
          default: Priority
        type: object
      template:
        description: The rendering template.
        x-label:
          default: Rendering Template
        type: string
  media_file:
    properties:
      abs_url:
        description: The absolute URL with request protocol (read only)
        type: string
      alt:
        additionalProperties:
          type: string
        description: The alternative image text
        format: localized
        type: object
      dis_base_url:
        description: The DIS base URL only for product images
        type: string
      path:
        description: "The raw media file path\n (only this needs to be provided in\
          \ update request)"
        type: string
      title:
        additionalProperties:
          type: string
        description: The image title
        format: localized
        type: object
  markup_text:
    properties:
      markup:
        description: The rendered HTML (read only)
        type: string
      source:
        description: "The raw markup text\n (only this needs to be provided in update\
          \ request)"
        type: string
paths:
  /libraries/{library_id}/content/{content_id}:
    delete:
      description: Deletes the content asset with the specified ID from the specified
        library. If the content asset is not found, the server returns a 404 (NotFoundException)
        fault. If the content asset is locked by another user, the server returns
        a 409 (ResourceLockedException) fault. If the connection is not secure, the
        server returns a 403 (SecureCommunicationRequiredException) fault.
      operationId: deleteLibrariesByIDContentByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to remove.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      responses:
        '412':
          description: '`ResourceLockedException` - Indicates that the ID from the
            request body doesn''t match the URL-Id.'
        '204':
          description: ''
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ContentNotFoundException` - Indicates that the
            content asset with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
    get:
      description: Returns a content asset using the specified ID. If the content
        asset cannot be found, the server returns a 404 (ContentNotFoundException)
        fault. If the connection is not secure, the server returns a 403 (SecureCommunicationRequiredException).
      operationId: getLibrariesByIDContentByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to retrieve.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_asset'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ContentNotFoundException` - Indicates that the
            content asset with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
    patch:
      description: 'Updates a content asset. In the request, the If-Match header is
        required. The value of the header is an ''ETag'' representing the last known
        base-point information for the content asset. If the header is missing, the
        server returns a 409 (IfMatchRequiredException) fault. If the header value
        does not match the server''s ''ETag'', the server returns a 412 (InvalidIfMatchException)
        fault. The delta information for the library folder containing the content
        asset is updated atomically: the information is written completely or not
        at all. If the content asset is locked, the server returns a 409 (ResourceLockedException)
        fault.'
      operationId: patchLibrariesByIDContentByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to retrieve.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/content_asset'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_asset'
        '400':
          description: '`ContentIdAlreadyInUseException` - Indicates that a content
            asset with the ID to change to is already existing.'
        '412':
          description: '`ResourceLockedException` - Indicates that the ID from the
            request body doesn''t match the URL-Id.'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ContentNotFoundException` - Indicates that the
            content asset with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
    put:
      description: 'Creates a new content asset in the specified library, or overwrites
        an existing content asset. If a content asset with the specified ID already
        exists, the server completely overwrites the content asset. Please note: Existing
        folder assignments are not touched. If the existing content asset is locked,
        the server returns a 409 (ResourceLockedException) fault. If the connection
        is not secure, the server returns a 403 (SecureCommunicationRequiredException)
        fault.'
      operationId: putLibrariesByIDContentByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to retrieve.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/content_asset'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_asset'
        '400':
          description: '`IdConflictException` - Indicates that the ID from the request
            body doesn''t match the URL-Id.'
        '412':
          description: '`ResourceLockedException` - Indicates that the ID from the
            request body doesn''t match the URL-Id.'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ContentNotFoundException` - Indicates that the
            content asset with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
