swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  content_folder_assignment:
    description: Document representing a content folder assignment.
    properties:
      content_id:
        description: The content id.
        maxLength: 256
        type: string
      content_link:
        description: The content link.
        type: string
      default:
        description: A flag indicating whether the assignment is the default one.
        type: boolean
      folder_id:
        description: The folder id.
        maxLength: 256
        type: string
      folder_link:
        description: The folder link.
        type: string
      position:
        description: The position of the content asset in the folder.
        format: double
        minimum: 0
        type: number
paths:
  /libraries/{library_id}/folder_assignments/{content_id}/{folder_id}:
    delete:
      description: Action to unassign a content asset from the specified library folder.
      operationId: deleteLibrariesByIDFolderAssignmentsByIDByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to retrieve.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - description: ID of a target folder.
        in: path
        maxLength: 256
        minLength: 1
        name: folder_id
        required: true
        type: string
      responses:
        '204':
          description: ''
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ParentFolderNotFoundException` - Indicates that
            the parent folder with the given id is unknown. or `ContentNotFoundException`
            - Indicates that the content asset with the given id is unknown. or `AssignmentNotFoundException`
            - Indicates that no assignment between the given content asset and folder
            exists'
      security:
      - oauth2_application: []
      tags:
      - libraries
    get:
      description: Action to get a single content to folder assignment
      operationId: getLibrariesByIDFolderAssignmentsByIDByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the ID of the content asset to retrieve.
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - description: ID of a target folder.
        in: path
        maxLength: 256
        minLength: 1
        name: folder_id
        required: true
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_folder_assignment'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ParentFolderNotFoundException` - Indicates that
            the parent folder with the given id is unknown. or `ContentNotFoundException`
            - Indicates that the content asset with the given id is unknown. or `AssignmentNotFoundException`
            - Indicates that no assignment between the given content asset and folder
            exists'
      security:
      - oauth2_application: []
      tags:
      - libraries
    patch:
      description: Action to update a single content to folder assignment. Currently
        only the position and default attribute can be changed.
      operationId: patchLibrariesByIDFolderAssignmentsByIDByID
      parameters:
      - description: ID of the shared library or the site-id in case of a private
          library.
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the content id of the assignment
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - description: ID of a target folder.
        in: path
        maxLength: 256
        minLength: 1
        name: folder_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/content_folder_assignment'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_folder_assignment'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `FolderNotFoundException` - Indicates that the
            folder with the given id is unknown. or `ContentNotFoundException` - Indicates
            that the content asset with the given id is unknown. or `AssignmentNotFoundException`
            - Indicates that no assignment between the given content asset and folder
            exists.'
      security:
      - oauth2_application: []
      tags:
      - libraries
    put:
      description: Action to assign a content asset to a specified folder.
      operationId: putLibrariesByIDFolderAssignmentsByIDByID
      parameters:
      - description: the ID of the shared library or the site-id in case of a private
          library
        in: path
        maxLength: 256
        minLength: 1
        name: library_id
        required: true
        type: string
      - description: the content id
        in: path
        maxLength: 256
        minLength: 1
        name: content_id
        required: true
        type: string
      - description: the folder id
        in: path
        maxLength: 256
        minLength: 1
        name: folder_id
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/content_folder_assignment'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/content_folder_assignment'
        '404':
          description: '`LibraryNotFoundException` - Indicates that library with the
            given id is unknown. or `ParentFolderNotFoundException` - Indicates that
            the parent folder with the given id is unknown. or `ContentNotFoundException`
            - Indicates that the content asset with the given id is unknown.'
      security:
      - oauth2_application: []
      tags:
      - libraries
