swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  menu_action:
    description: Document representing a menu action.
    properties:
      description:
        additionalProperties:
          type: string
        description: The description of the menu action.
        format: localized
        type: object
      display_name:
        additionalProperties:
          type: string
        description: The display name of the menu action.
        format: localized
        type: object
      module_type:
        description: The module type of the menu action (BM or CC).
        type: string
      name:
        description: The name of the menu action.
        type: string
      system:
        description: "{@code true} if the menu action is a system menu action. {@code\
          \ false} if the menu action is a custom menu\n action."
        type: boolean
      type:
        description: The permission type.
        type: string
      values:
        description: The list of possible values for the menu action, e.g. ACCESS
          or READONLY.
        items:
          type: string
        type: array
  menu_item:
    description: Document representing a menu item.
    properties:
      display_name:
        additionalProperties:
          type: string
        description: The display name of the menu item.
        format: localized
        type: object
      menu_actions:
        description: The collection of available menu actions.
        items:
          $ref: '#/definitions/menu_action'
        type: array
      module_type:
        description: The module type of the menu item (BM or CC).
        type: string
      name:
        description: The name of the menu item.
        type: string
      type:
        description: The permission type.
        type: string
  module_permissions:
    description: Document representing the available module permissions in shape of
      menu items and menu actions.
    properties:
      organization:
        description: The collection of available organization menu items.
        items:
          $ref: '#/definitions/menu_item'
        type: array
      scopes:
        description: The available menu item scopes (e.g. organization, site).
        items:
          type: string
        type: array
      site:
        description: The list of available site menu items.
        items:
          $ref: '#/definitions/menu_item'
        type: array
paths:
  /permissions/bm/module:
    get:
      description: Get Business Manager module permissions per scope.
      operationId: getPermissionsBmModule
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/module_permissions'
      security:
      - oauth2_application: []
      tags:
      - permissions
