swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  webdav_permissions:
    description: Document representing the available WebDAV permissions.
    properties:
      scopes:
        description: The available WebDAV permission scopes (e.g. unscoped).
        items:
          type: string
        type: array
      unscoped:
        description: The collection of available unscoped WebDAV permissions.
        items:
          $ref: '#/definitions/webdav_permission'
        type: array
  webdav_permission:
    description: Document representing a WebDAV permission.
    properties:
      description:
        additionalProperties:
          type: string
        description: The description of the WebDAV permission.
        format: localized
        type: object
      folder:
        description: The folder of the WebDAV permission.
        type: string
      type:
        description: The permission type.
        type: string
      values:
        description: The list of possible values for the WebDAV permission, e.g. ACCESS
          or READONLY.
        items:
          type: string
        type: array
paths:
  /permissions/bm/webdav:
    get:
      description: Get WebDAV permissions per scope.
      operationId: getPermissionsBmWebdav
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/webdav_permissions'
      security:
      - oauth2_application: []
      tags:
      - permissions
