swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  variation_attribute:
    description: Document representing a variation attribute.
    properties:
      attribute_definition_id:
        description: The id of the requested attribute definition.
        type: string
      attribute_definition_name:
        additionalProperties:
          type: string
        description: The localized display name of the variation attribute definition.
        format: localized
        type: object
      default_value:
        description: default variation attribute value
        type: string
      id:
        description: The id of the variation attribute.
        minLength: 1
        type: string
      link:
        description: URL that is used to get this instance
        type: string
      name:
        additionalProperties:
          type: string
        description: The localized display name of the variation attribute.
        format: localized
        type: object
      shared:
        description: Returns the value of attribute 'shared' if attribute is local
          or shared
        type: boolean
      slicing:
        description: Returns the value of attribute 'slicing'.
        type: boolean
      values:
        description: The sorted array of variation values. This array can be empty.
        items:
          $ref: '#/definitions/variation_attribute_value'
        type: array
      variation_attribute_type:
        description: variation attribute type
        enum:
        - string
        - int
        - unknown
        type: string
    required:
    - attribute_definition_id
  media_file:
    properties:
      abs_url:
        description: The absolute URL with request protocol (read only)
        type: string
      alt:
        additionalProperties:
          type: string
        description: The alternative image text
        format: localized
        type: object
      dis_base_url:
        description: The DIS base URL only for product images
        type: string
      path:
        description: "The raw media file path\n (only this needs to be provided in\
          \ update request)"
        type: string
      title:
        additionalProperties:
          type: string
        description: The image title
        format: localized
        type: object
  variation_attribute_value:
    description: Document representing a variation attribute value.
    properties:
      description:
        additionalProperties:
          type: string
        description: The localized description of the variation value.
        format: localized
        type: object
      image:
        $ref: '#/definitions/media_file'
        description: The first product image for the configured viewtype and this
          variation value.
      image_swatch:
        $ref: '#/definitions/media_file'
        description: The first product image for the configured viewtype and this
          variation value. (typically the swatch image)
      link:
        description: ''
        type: string
      name:
        additionalProperties:
          type: string
        description: The localized display name of the variation value.
        format: localized
        type: object
      orderable:
        description: A flag indicating whether at least one variant with this variation
          attribute value is available to sell.
        type: boolean
      position:
        description: The position of the value among all values of a variation attribute.
        format: double
        type: number
      value:
        description: The actual variation value.
        minLength: 1
        type: string
    required:
    - value
  variant:
    description: Document representing a product variation.
    properties:
      ats:
        description: Inventory "Available to Sell" of the product.
        format: double
        type: number
      default_product_variation:
        description: ''
        type: boolean
      image:
        $ref: '#/definitions/media_file'
        description: URL to the preview image.
      in_stock:
        description: '`true` if the product is in stock, or `false` if not.'
        type: boolean
      link:
        description: The URL addressing the product.
        type: string
      online:
        description: "If the product is currently online.\n `true` if online\n `false`\
          \ if not"
        type: boolean
      orderable:
        description: A flag indicating whether the variant is orderable.
        type: boolean
      price:
        description: The sales price of the variant.
        format: double
        type: number
      price_currency:
        description: Currency code for the price of the product.
        type: string
      price_per_unit:
        description: The sales price of the variant.
        format: double
        type: number
      product_id:
        description: The id (SKU) of the variant.
        maxLength: 100
        minLength: 1
        type: string
      searchable:
        additionalProperties:
          type: boolean
        description: ''
        format: site-specific
        type: object
      variation_attributes:
        description: variation attributes
        items:
          $ref: '#/definitions/variation_attribute'
        type: array
      variation_values:
        additionalProperties:
          type: string
        description: The actual variation attribute id - value pairs.
        type: object
    required:
    - product_id
paths:
  /products/{master_product_id}/variations/{id}:
    delete:
      description: "Unassign a variation product from a product master.  The variation\
        \ product is not deleted: it remains as a\n normal product after unsassign."
      operationId: deleteProductsByIDVariationsByID
      parameters:
      - description: ''
        in: path
        minLength: 1
        name: master_product_id
        required: true
        type: string
      - description: ''
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      responses:
        '400':
          description: '`ProductNotMasterException` - Indicates the master product
            id does not represent a master product. or `ProductIsNotVariationException`
            - Indicates product specified is not a variation.'
        '204':
          description: ''
        '404':
          description: '`ProductNotFoundException` - Indicates either the master product
            or the variation product cannot be found. or `VariationNotFoundException`
            - Indicates the product does not belong to the master product.'
      security:
      - oauth2_application: []
      tags:
      - products
    get:
      description: Read a variation for a product master.
      operationId: getProductsByIDVariationsByID
      parameters:
      - description: The id of the master product that contains the variation.
        in: path
        minLength: 1
        name: master_product_id
        required: true
        type: string
      - description: The id of the variation product.
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: ''
        in: query
        name: site_id
        type: string
      - description: The valid expands are {variation,attributes,availability,prices}
        in: query
        items:
          type: string
        name: expand
        type: array
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/variant'
        '400':
          description: '`ProductNotMasterException` - Indicates the master product
            id does not represent a master product. or `ProductIsNotVariationException`
            - Indicates the product specified is not a variation.'
        '404':
          description: '`ProductNotFoundException` - Indicates either the master product
            or the variation product cannot be found. or `VariationNotFoundException`
            - Indicates the product does not belong to the master product.'
      security:
      - oauth2_application: []
      tags:
      - products
    patch:
      description: Update a variation for a product master.
      operationId: patchProductsByIDVariationsByID
      parameters:
      - description: The id of the master product that contains the variation.
        in: path
        minLength: 1
        name: master_product_id
        required: true
        type: string
      - description: The id of the variation product.
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/variant'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/variant'
        '400':
          description: '`ProductNotMasterException` - Indicates the master product
            id does not represent a master product. or `ProductIsNotVariationException`
            - Indicates product specified is not a variation. or `VariationValueNotValidException`
            - Indicates the values passed are not valid for the variation attributes.'
        '404':
          description: '`ProductNotFoundException` - Indicates either the master product
            or the variation product cannot be found. or `VariationNotFoundException`
            - Indicates the product does not belong to the master product.'
      security:
      - oauth2_application: []
      tags:
      - products
    put:
      description: "Assign a variation for a product master.  If the variation product\
        \ does not initially exist,\n one is created using the body passed in."
      operationId: putProductsByIDVariationsByID
      parameters:
      - description: The id of the master product that contains the variation.
        in: path
        minLength: 1
        name: master_product_id
        required: true
        type: string
      - description: The id of the variation product.
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/variant'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/variant'
        '400':
          description: '`ProductNotMasterException` - Indicates the master product
            id does not represent a master product. or `VariationValueNotValidException`
            - Indicates the values passed are not valid for the variation attributes.'
        '404':
          description: '`ProductNotFoundException` - Indicates either the master product
            or the variation product cannot be found. or `VariationAttributeValueNotFoundException`
            - Indicates the value passed into a variation attribute is not one found
            in the valid values.'
      security:
      - oauth2_application: []
      tags:
      - products
