swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  variation_attribute_values:
    description: Document representing an unfiltered list of variation attribute values.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        description: ''
        items:
          $ref: '#/definitions/variation_attribute_value'
        type: array
      expand:
        description: The list of expands set for the search request. Expands are optional.
        items:
          type: string
        type: array
      next:
        description: The URL of the next result page.
        type: string
      previous:
        description: The URL of the previous result page.
        type: string
      select:
        description: The fields that you want to select.
        type: string
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  media_file:
    properties:
      abs_url:
        description: The absolute URL with request protocol (read only)
        type: string
      alt:
        additionalProperties:
          type: string
        description: The alternative image text
        format: localized
        type: object
      dis_base_url:
        description: The DIS base URL only for product images
        type: string
      path:
        description: "The raw media file path\n (only this needs to be provided in\
          \ update request)"
        type: string
      title:
        additionalProperties:
          type: string
        description: The image title
        format: localized
        type: object
  variation_attribute_value:
    description: Document representing a variation attribute value.
    properties:
      description:
        additionalProperties:
          type: string
        description: The localized description of the variation value.
        format: localized
        type: object
      image:
        $ref: '#/definitions/media_file'
        description: The first product image for the configured viewtype and this
          variation value.
      image_swatch:
        $ref: '#/definitions/media_file'
        description: The first product image for the configured viewtype and this
          variation value. (typically the swatch image)
      link:
        description: ''
        type: string
      name:
        additionalProperties:
          type: string
        description: The localized display name of the variation value.
        format: localized
        type: object
      orderable:
        description: A flag indicating whether at least one variant with this variation
          attribute value is available to sell.
        type: boolean
      position:
        description: The position of the value among all values of a variation attribute.
        format: double
        type: number
      value:
        description: The actual variation value.
        minLength: 1
        type: string
    required:
    - value
paths:
  /products/{product_id}/variation_attributes/{attribute_id}/values:
    get:
      description: Reads variation attribute values of a variation attribute bound
        to a product.
      operationId: getProductsByIDVariationAttributesByIDValues
      parameters:
      - description: id of the product
        in: path
        minLength: 1
        name: product_id
        required: true
        type: string
      - description: The variation attribute ID that contains the values.
        in: path
        minLength: 1
        name: attribute_id
        required: true
        type: string
      - description: ''
        in: query
        name: site_id
        type: string
      - description: the first record to get in the page
        format: int32
        in: query
        name: start
        type: integer
      - description: the number of records to get
        format: int32
        in: query
        name: count
        type: integer
      - description: a string that specifies which fields to return (default is all).
        in: query
        name: select
        type: string
      - description: 'set of expands to retrieve additional information: {availability,
          image}'
        in: query
        items:
          type: string
        name: expand
        type: array
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/variation_attribute_values'
        '400':
          description: '`ProductNotMasterException` - Indicates the master product
            is not found.'
        '404':
          description: '`ProductNotFoundException` - Indicates the product is not
            found. or `VariationAttributeNotFoundException` - If the attribute id
            specified is not a valid product attribute.'
      security:
      - oauth2_application: []
      tags:
      - products
