swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  shipping_address_update_request:
    description: Request body to update the order shipping address.
    properties:
      address1:
        type: string
      address2:
        type: string
      city:
        type: string
      company_name:
        type: string
      country_code:
        type: string
      first_name:
        type: string
      full_name:
        x-label:
          default: Full Name
        type: string
      id:
        type: string
      job_title:
        type: string
      last_name:
        type: string
      phone:
        type: string
      post_box:
        type: string
      postal_code:
        type: string
      salutation:
        type: string
      second_name:
        type: string
      state_code:
        type: string
      suffix:
        type: string
      suite:
        type: string
      title:
        type: string
paths:
  /sites/{site_id}/orders/{order_no}/shipments/{shipment_id}/shipping_address:
    put:
      description: Updates (create or replace) the order shipment address.
      operationId: putSitesByIDOrdersByIDShipmentsByIDShippingAddress
      parameters:
      - description: ID of the site
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The order number
        in: path
        minLength: 1
        name: order_no
        required: true
        type: string
      - description: ID of the shipment
        in: path
        minLength: 1
        name: shipment_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/shipping_address_update_request'
      responses:
        '204':
          description: ''
        '404':
          description: '`OrderNotFoundException` - In case of the given order_no does
            not reference an existing order. or `SiteNotFoundException` - In case
            of the given site_id does not reference an existing site. or `ShipmentNotFoundException`
            - In case of the given shipment_id does not reference an existing shipment.'
      security:
      - oauth2_application: []
      - client_id: []
      tags:
      - sites
