swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  result_page:
    description: Data that can be used to get the next and previous page of a Data
      API results object.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        type: integer
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        type: integer
  query:
    description: "Document representing a query. A query contains a set of objects\
      \ that define criteria\n used to select records. A query can contain one of\
      \ the following:\n"
  source_code_specification:
    description: Document representing a source code specification
    properties:
      expression:
        description: "Expression is a value for the \"Source Code Specification\"\
          \ may be a literal source code, or it may contain wildcards.\n A literal\
          \ code is simply the literal code. Valid characters are letters and numbers\
          \ (no spaces).\n A wildcard allows a single source code specification to\
          \ match multiple source codes. The following wildcards are supported:\n\
          \ - ? - Matches any single alpha-numeric character. For example: the source\
          \ code specification 'ABC?' would match 'ABCD' or 'ABC3', but not 'ABCDE'.\n\
          \ - * - Matches any sequence of alpha-numeric characters. For example: the\
          \ source code specification 'ABC*' would match 'ABCD', 'ABCDE', or 'ABC123'.\n\
          \ - [n1..n2] - Matches any number from n1 through and including n2.\n For\
          \ example: the source code specification 'ABC[3..22]' would match 'ABC3',\
          \ 'ABC4' or 'ABC22', but not 'ABC33' or 'ABCD'."
        type: string
  source_code_group:
    description: Document representing a source code group
    properties:
      active:
        description: The active flag, a computed value based on start and end time
        type: boolean
      active_redirect:
        $ref: '#/definitions/source_code_redirect_info'
        description: The active redirect information
      cookie_duration:
        description: The cookie duration in days
        format: int32
        maximum: 999
        minimum: 0
        type: integer
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      description:
        description: The description
        type: string
      enabled:
        description: The enabled flag for storefront to consider the source code group,
          default to false.
        type: boolean
      end_time:
        description: The end time
        format: date-time
        type: string
      id:
        description: The id of source code group
        x-label:
          default: ID
        maxLength: 28
        minLength: 1
        type: string
      inactive_redirect:
        $ref: '#/definitions/source_code_redirect_info'
        description: The inactive redirect information
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: URL that is used to get this instance, read only
        type: string
      specifications:
        description: Source Code specifications
        items:
          $ref: '#/definitions/source_code_specification'
        type: array
      start_time:
        description: The start time
        format: date-time
        type: string
  source_code_group_search_result:
    description: Document representing a source code group search result.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        items:
          type: object
        type: array
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        minimum: 0
        type: integer
      expand:
        description: List of expansions to be applied to each search results. Expands
          are optional
        items:
          type: string
        type: array
      hits:
        description: The sorted array of search hits. Can be empty.
        items:
          $ref: '#/definitions/source_code_group'
        type: array
      next:
        $ref: '#/definitions/result_page'
        description: The URL of the next result page.
      previous:
        $ref: '#/definitions/result_page'
        description: The URL of the previous result page.
      query:
        $ref: '#/definitions/query'
        description: The query passed into the search
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The fields that you want to select.
        type: string
      sorts:
        description: The list of sort clauses configured for the search request. Sort
          clauses are optional.
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  search_request:
    description: Document representing a search request for retrieving items within
      the Data API. The query is a potentially complex set of expressions. The fields
      that each query supports are defined within the search resource.
    properties:
      count:
        description: The number of returned documents
        format: int32
        maximum: 200
        minimum: 1
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        minimum: 0
        type: integer
      expand:
        description: List of expansions to be applied to each search results. Expands
          are optional
        items:
          type: string
        type: array
      query:
        $ref: '#/definitions/query'
        description: The query to apply
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The field to be selected.
        type: string
      sorts:
        description: The list of sort clauses configured for the search request. Sort
          clauses are optional.
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
    required:
    - query
  sort:
    description: Document representing a sort request.
    properties:
      field:
        description: The name of the field to sort on.
        type: string
      sort_order:
        description: The sort order to be applied when sorting. When omitted, the
          default sort order (ASC) is used.
        enum:
        - asc
        - desc
        type: string
    required:
    - field
  source_code_redirect_info:
    description: Document representing a source code redirect info
    properties:
      location:
        description: The location of redirect, based on the type, this can be a product
          location, category location, home page, content page, or just a URL
        type: string
      location_type:
        description: The type of redirect location, e.g. product (for a product page),
          category (a category page), home (for home page), page (for content), url
          (for a URL location)
        enum:
        - default
        - home
        - product
        - category
        - page
        - url
        type: string
paths:
  /sites/{site_id}/source_code_group_search:
    post:
      description: "Searches for source code groups.\n \n The query attribute specifies\
        \ a complex query that can be used to narrow down the search. These are the\
        \ list\n of searchable attributes:\n \n - id - String\n - description - String\n\
        \ - source_code* - String \n - start_time - DateTime\n - end_time - DateTime\n\
        \ - creation_date - DateTime\n - enabled - Boolean\n - active* - Boolean \n\
        \ \n\n * - These fields can only be used in Queries as conjunctions (using\
        \ AND).  If the field is used in a disjunction\n (OR) an exception will be\
        \ thrown.\n \n The output of the query can also be sorted. These are the list\
        \ of sortable attributes:\n \n - id - String\n - description - String\n -\
        \ enabled - Boolean\n - creation_date - DateTime\n \n \n Expands that can\
        \ be applied for the search request\n \n - specifications - String\n "
      operationId: postSitesByIDSourceCodeGroupSearch
      parameters:
      - description: The id of the site.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/search_request'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/source_code_group_search_result'
        '400':
          description: '`MalformedSearchParameterException` - Thrown if the query
            is ill-formed.'
      security:
      - oauth2_application: []
      tags:
      - sites
