swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions: {}
paths:
  /sites/{site_id}/campaigns/{campaign_id}/customer_groups/{customer_group_id}:
    delete:
      description: Action to unbind a customer group from a given campaign.
      operationId: deleteSitesByIDCampaignsByIDCustomerGroupsByID
      parameters:
      - description: ''
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The campaign ID that coupons are to be unbound from
        in: path
        minLength: 1
        name: campaign_id
        required: true
        type: string
      - description: The customer group ID to unbind from a campaign
        in: path
        minLength: 1
        name: customer_group_id
        required: true
        type: string
      responses:
        '400':
          description: '`ConstraintViolationException` - Indicates some parameter
            constraint violation occurs'
        '204':
          description: ''
        '404':
          description: "`CampaignNotFoundException` - Indicates that the campaign\
            \ with the given campaign id\n              is unknown."
      security:
      - oauth2_application: []
      tags:
      - sites
    put:
      description: Action to bind a single customer group to a given campaign.
      operationId: putSitesByIDCampaignsByIDCustomerGroupsByID
      parameters:
      - description: ''
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The campaign ID that coupons are to be bound to
        in: path
        minLength: 1
        name: campaign_id
        required: true
        type: string
      - description: The customer group ID to bind to a campaign
        in: path
        minLength: 1
        name: customer_group_id
        required: true
        type: string
      responses:
        '400':
          description: '`ConstraintViolationException` - Indicates some parameter
            constraint violation occurs'
        '204':
          description: ''
        '404':
          description: "`CampaignNotFoundException` - Indicates that the campaign\
            \ with the given campaign id\n              is unknown."
      security:
      - oauth2_application: []
      tags:
      - sites
