swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions: {}
paths:
  /sites/{site_id}/campaigns/{campaign_id}/sorting_rules/{sorting_rule_id}/{category_id}:
    delete:
      description: Action to unbind a single sorting rule from a given campaign.
      operationId: deleteSitesByIDCampaignsByIDSortingRulesByIDByID
      parameters:
      - description: The ID of the site that contains the campaign, sorting rule and
          category.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The ID of the campaign to which the sorting rule is to be assigned.
        in: path
        minLength: 1
        name: campaign_id
        required: true
        type: string
      - description: The ID of sorting rule that is to be assigned to the campaign.
        in: path
        minLength: 1
        name: sorting_rule_id
        required: true
        type: string
      - description: The ID of the category that is associated with the sorting rule.
        in: path
        minLength: 1
        name: category_id
        required: true
        type: string
      - description: The context in which the rule lives, either "site" or "global"the
          optional context of the sorting rule, either "site" (default) or "global"
        in: query
        name: rule_context
        type: string
      responses:
        '400':
          description: '`InvalidCategoryException` - Indicates that the category with
            the given category ID is not found.'
        '204':
          description: ''
        '404':
          description: '`SiteNotFoundException` - thrown when site with the given
            site id is not found. or `CampaignNotFoundException` - Indicates that
            the campaign with the given campaign ID is not found. or `SortingRuleNotFoundException`
            - Indicates that the sorting rule with the given sorting rule ID is not
            found.'
      security:
      - oauth2_application: []
      tags:
      - sites
    put:
      description: Action to bind a single sorting rule to a given campaign.
      operationId: putSitesByIDCampaignsByIDSortingRulesByIDByID
      parameters:
      - description: The ID of the site that contains the campaign, sorting rule and
          category.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The ID of the campaign to which the sorting rule is to be assigned.
        in: path
        minLength: 1
        name: campaign_id
        required: true
        type: string
      - description: The ID of sorting rule that is to be assigned to the campaign.
        in: path
        minLength: 1
        name: sorting_rule_id
        required: true
        type: string
      - description: The ID of the category that is associated with the sorting rule.
        in: path
        minLength: 1
        name: category_id
        required: true
        type: string
      - description: The context in which the rule lives, either "site" or "global"the
          optional context of the sorting rule, either "site" (default) or "global"
        in: query
        name: rule_context
        type: string
      responses:
        '400':
          description: '`InvalidCategoryException` - Indicates that the category with
            the given category ID is not found.'
        '204':
          description: ''
        '404':
          description: '`SiteNotFoundException` - thrown when site with the given
            site id is not found. or `CampaignNotFoundException` - Indicates that
            the campaign with the given campaign ID is not found. or `SortingRuleNotFoundException`
            - Indicates that the sorting rule with the given sorting rule ID is not
            found.'
        '409':
          description: "`SortingRuleCampaignAssignConflictException` - Indicates that\
            \ there is a sorting rule already assigned to the given campaign ID and\
            \ category ID.\n              The sorting rule with the given sorting\
            \ rule ID cannot be assigned to the same campaign ID and category ID."
      security:
      - oauth2_application: []
      tags:
      - sites
