swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  gift_certificate:
    description: Document representing a gift certificate
    properties:
      amount:
        $ref: '#/definitions/money'
        description: "The gift certificate amount.\n The user cannot change the gift\
          \ certificate amount after the creation of the gift certificate."
      balance:
        $ref: '#/definitions/money'
        description: "The gift certificate balance.\n This is a computed attribute\
          \ and cannot be modified."
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      description:
        description: The description of the gift certificate.
        x-label:
          default: Description
        maxLength: 4000
        type: string
      enabled:
        description: The enabled flag of the gift certificate.
        x-label:
          default: Enabled
        type: boolean
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: "The URL to get the gift certificate.\n This is a computed attribute\
          \ and cannot be modified."
        type: string
      masked_gift_certificate_code:
        description: "The masked gift certificate code with all but the\n last 4 characters\
          \ replaced with a '*' character.\n This is a computed attribute and cannot\
          \ be modified."
        type: string
      merchant_id:
        description: "The merchant ID of the gift certificate.\n This is a unique\
          \ attribute.\n This is a computed attribute and cannot be modified.\n This\
          \ is used to get, update and the delete gift certificates."
        x-label:
          default: Merchant ID
        type: string
      message:
        description: The message to the recipient of the gift certificate.
        x-label:
          default: Message
        maxLength: 4000
        type: string
      order_no:
        description: The order number of the gift certificate.
        x-label:
          default: Order Number
        type: string
      recipient_email:
        description: The email address of the recipient of the gift certificate.
        x-label:
          default: Recipient Email
        type: string
      recipient_name:
        description: The recipient of the gift certificate.
        x-label:
          default: Recipient Name
        maxLength: 256
        type: string
      sender_name:
        description: The sender of the gift certificate.
        x-label:
          default: Sender Name
        maxLength: 256
        type: string
      status:
        description: "The status of the gift certificate.\n While creating a gift\
          \ certificate, user can set the status\n to either \"pending\" or \"issued\"\
          \ only."
        enum:
        - issued
        - partially_redeemed
        - pending
        - redeemed
        x-label:
          default: Status
        type: string
      transactions:
        description: The transactions of the gift certificate. This attribute is only
          available as part of the response.
        items:
          $ref: '#/definitions/account_transaction'
        type: array
  account_transaction:
    description: Document representing an account transaction
    properties:
      amount:
        $ref: '#/definitions/money'
        description: The amount of the gift certificate
      order_no:
        description: The order number of the gift certificate
        type: string
      timestamp:
        description: The timestamp of the transaction of the gift certificate
        format: date-time
        type: string
      type_code:
        description: The type code of the gift certificate
        enum:
        - create
        - redeem
        - delete
        - enable
        - disable
        type: string
  result_page:
    description: Data that can be used to get the next and previous page of a Data
      API results object.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        type: integer
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        type: integer
  query:
    description: "Document representing a query. A query contains a set of objects\
      \ that define criteria\n used to select records. A query can contain one of\
      \ the following:\n"
  gift_certificate_search_result:
    description: Document representing a gift certificate search result.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        items:
          type: object
        type: array
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        minimum: 0
        type: integer
      expand:
        description: List of expansions to be applied to each search results. Expands
          are optional
        items:
          type: string
        type: array
      hits:
        description: The sorted array of search hits. Can be empty.
        items:
          $ref: '#/definitions/gift_certificate'
        type: array
      next:
        $ref: '#/definitions/result_page'
        description: The URL of the next result page.
      previous:
        $ref: '#/definitions/result_page'
        description: The URL of the previous result page.
      query:
        $ref: '#/definitions/query'
        description: The query passed into the search
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The fields that you want to select.
        type: string
      sorts:
        description: The list of sort clauses configured for the search request. Sort
          clauses are optional.
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  money:
    properties:
      currency_mnemonic:
        description: The mnemonic for the money.
        type: string
      value:
        description: The value for the money.
        format: double
        type: number
  search_request:
    description: Document representing a search request for retrieving items within
      the Data API. The query is a potentially complex set of expressions. The fields
      that each query supports are defined within the search resource.
    properties:
      count:
        description: The number of returned documents
        format: int32
        maximum: 200
        minimum: 1
        type: integer
      db_start_record_:
        description: The zero-based index of the record that we want to start with,
          used to optimize special handling
        format: int32
        minimum: 0
        type: integer
      expand:
        description: List of expansions to be applied to each search results. Expands
          are optional
        items:
          type: string
        type: array
      query:
        $ref: '#/definitions/query'
        description: The query to apply
        x-sub_types:
          nested_query: '#/definitions/nested_query'
          filtered_query: '#/definitions/filtered_query'
          text_query: '#/definitions/text_query'
          match_all_query: '#/definitions/match_all_query'
          term_query: '#/definitions/term_query'
          bool_query: '#/definitions/bool_query'
      select:
        description: The field to be selected.
        type: string
      sorts:
        description: The list of sort clauses configured for the search request. Sort
          clauses are optional.
        items:
          $ref: '#/definitions/sort'
        type: array
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
    required:
    - query
  sort:
    description: Document representing a sort request.
    properties:
      field:
        description: The name of the field to sort on.
        type: string
      sort_order:
        description: The sort order to be applied when sorting. When omitted, the
          default sort order (ASC) is used.
        enum:
        - asc
        - desc
        type: string
    required:
    - field
paths:
  /sites/{site_id}/gift_certificate_search:
    post:
      description: "Searches for gift certificates.\n \n The query attribute specifies\
        \ a complex query that can be used to narrow down the search. These are the\
        \ list\n of searchable attributes:\n \n - merchant_id - String\n - masked_gift_certificate_code*\
        \ - String\n - order_no - String\n - sender_name - String\n - recipient_name\
        \ - String\n - recipient_email - String\n - status - String\n - enabled -\
        \ Boolean\n - message - String\n - description - String\n - creation_date\
        \ - Date\n - currency_mnemonic* - String\n \n\n * masked_gift_certificate_code,\
        \ also known as just code, can only be used in a term query.  If a\n four-character\
        \ code is supplied, it is assumed that the search is on the unmasked portion\
        \ of the code, otherwise\n the full code must be matched.  Text queries are\
        \ not allowed.\n\n * currency_mnemonic can only be joined with other attributes\
        \ using a conjunction (AND).\n\n Note that only searchable attributes can\
        \ be used in sorting.  The code attribute cannot be used for sorting."
      operationId: postSitesByIDGiftCertificateSearch
      parameters:
      - description: The id of the site.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/search_request'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/gift_certificate_search_result'
        '400':
          description: '`MalformedSearchParameterException` - Thrown if the query
            is ill-formed.'
      security:
      - oauth2_application: []
      tags:
      - sites
