swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  media_file:
    properties:
      abs_url:
        description: The absolute URL with request protocol (read only)
        type: string
      alt:
        additionalProperties:
          type: string
        description: The alternative image text
        format: localized
        type: object
      dis_base_url:
        description: The DIS base URL only for product images
        type: string
      path:
        description: "The raw media file path\n (only this needs to be provided in\
          \ update request)"
        type: string
      title:
        additionalProperties:
          type: string
        description: The image title
        format: localized
        type: object
  store:
    description: Document representing a store
    properties:
      address1:
        description: Returns the first address.
        x-label:
          default: Address 1
        maxLength: 256
        type: string
      address2:
        description: Returns the second address value.
        x-label:
          default: Address 2
        maxLength: 256
        type: string
      c_countryCodeValue:
        description: Country Code Value - for the form values
        x-label:
          default: Country Code Value
        type: string
      c_inventoryListId:
        description: Store Inventory List ID
        x-label:
          default: Store Inventory List ID
        type: string
      city:
        description: Returns the city.
        x-label:
          default: City
        maxLength: 256
        type: string
      country_code:
        description: The two-character country code per ISO 3166-1 alpha-2.
        enum:
        - CA
        - DE
        - US
        x-enum-labels:
        - default: Canada
        - default: Germany
        - default: United States
        x-label:
          default: Country
        maxLength: 2
        type: string
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      email:
        description: Email address to contact the store
        x-label:
          default: Email
        maxLength: 256
        type: string
      fax:
        description: Returns the fax number .
        x-label:
          default: Fax
        maxLength: 256
        type: string
      id:
        description: The id for the store
        x-label:
          default: ID
        maxLength: 256
        type: string
      image:
        $ref: '#/definitions/media_file'
        description: The image associated with the store
        x-label:
          default: Image
      inventory_id:
        description: The inventory list associated with the store
        x-label:
          default: Inventory List
        maxLength: 256
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      latitude:
        description: The latitude of the store
        format: double
        x-label:
          default: Latitude
        maximum: 90
        minimum: -90
        type: number
      link:
        description: a URL that is used to get this instance.  The property is computed
          and cannot be changed.
        x-label:
          default: Store document link
        type: string
      longitude:
        description: The longitude of the store
        format: double
        x-label:
          default: Longitude
        maximum: 180
        minimum: -180
        type: number
      name:
        description: The name of the store
        x-label:
          default: Name
        type: string
      phone:
        description: Returns the phone number.
        x-label:
          default: Phone
        maxLength: 256
        type: string
      pos_enabled:
        description: Whether this store uses our Store product for Point-of-Sale
        x-label:
          default: Uses Commerce Cloud Store for Point-of-Sale
        type: boolean
      postal_code:
        description: The postal code for the store
        x-label:
          default: Postal Code
        maxLength: 10
        type: string
      state_code:
        description: Returns the customer's state.
        x-label:
          default: State
        maxLength: 256
        type: string
      store_events:
        additionalProperties:
          $ref: '#/definitions/markup_text'
        description: The store events (localized)
        format: localized
        x-label:
          default: Store Events
        type: object
      store_hours:
        additionalProperties:
          $ref: '#/definitions/markup_text'
        description: The store opening hours (localized)
        format: localized
        x-label:
          default: Store Hours
        type: object
      store_locator_enabled:
        description: Whether this store should appear in store locator searches
        x-label:
          default: Store Locator Enabled
        type: boolean
  stores:
    description: Document representing an unfiltered list of stores.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        description: ''
        items:
          $ref: '#/definitions/store'
        type: array
      expand:
        description: The list of expands set for the search request. Expands are optional.
        items:
          type: string
        type: array
      next:
        description: The URL of the next result page.
        type: string
      previous:
        description: The URL of the previous result page.
        type: string
      select:
        description: The fields that you want to select.
        type: string
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  markup_text:
    properties:
      markup:
        description: The rendered HTML (read only)
        type: string
      source:
        description: "The raw markup text\n (only this needs to be provided in update\
          \ request)"
        type: string
paths:
  /sites/{site_id}/stores:
    get:
      description: Action to get all the stores with no filtering.
      operationId: getSitesByIDStores
      parameters:
      - description: ''
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: Optional start index for retrieving the items from a given index
          (default 0).
        format: int32
        in: query
        name: start
        type: integer
      - description: Optional count for retrieving only a subset of the items (default
          is 25).
        format: int32
        in: query
        name: count
        type: integer
      - description: The property selector.
        in: query
        name: select
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/stores'
      security:
      - oauth2_application: []
      tags:
      - sites
