swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions: {}
paths:
  /sites/{site_id}/ab_tests/{ab_test_id}/segments/{segment_id}/slot_configurations/{slot_id}/{slot_config_id}:
    delete:
      description: Action to unbind a slot configuration from a given abTest.
      operationId: deleteSitesByIDAbTestsByIDSegmentsByIDSlotConfigurationsByIDByID
      parameters:
      - description: The id of the abTest
        in: path
        minLength: 1
        name: ab_test_id
        required: true
        type: string
      - description: ''
        in: path
        minLength: 1
        name: segment_id
        required: true
        type: string
      - description: The id of the site
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The of the slot
        in: path
        minLength: 1
        name: slot_id
        required: true
        type: string
      - description: The id of the slot configuration
        in: path
        minLength: 1
        name: slot_config_id
        required: true
        type: string
      - description: "The context string, which consists of three parts: the context\
          \ type (which must be folder,\n                    category or global),\
          \ an equals sign (=), and the context id (either the category id or folder\
          \ id)."
        in: query
        minLength: 1
        name: context
        type: string
      responses:
        '400':
          description: '`InvalidContextTypeException` - Indicates the slot context
            type is not one of "global", "category", or "folder"'
        '204':
          description: ''
        '404':
          description: '`ABTestNotFoundException` - Indicates that the abTest with
            the given abTest ID is not found. or `SlotWithContextTypeNotFoundException`
            - Indicates that the slot with the given slot ID and context type is not
            found. or `SlotConfigurationIdentifierNotFoundException` - Indicates that
            the slot with the given slot ID, slot configuration ID and context type
            is not found. or `ABTestSegmentNotFoundException` - thrown when the segment
            with the given id is not found. or `SiteNotFoundException` - thrown when
            the site with the given id is not found.'
      security:
      - oauth2_application: []
      tags:
      - sites
    put:
      description: Action to bind a slot configuration to a given abTest.
      operationId: putSitesByIDAbTestsByIDSegmentsByIDSlotConfigurationsByIDByID
      parameters:
      - description: The id of the abTest
        in: path
        minLength: 1
        name: ab_test_id
        required: true
        type: string
      - description: ''
        in: path
        minLength: 1
        name: segment_id
        required: true
        type: string
      - description: The id of the site
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The of the slot
        in: path
        minLength: 1
        name: slot_id
        required: true
        type: string
      - description: The id of the slot configuration
        in: path
        minLength: 1
        name: slot_config_id
        required: true
        type: string
      - description: "The context string, which consists of three parts: the context\
          \ type (which must be folder,\n                    category or global),\
          \ an equals sign (=), and the context id (either the category id or folder\
          \ id).\n                    If you do not set this query parameter, the\
          \ global context is used by default."
        in: query
        minLength: 1
        name: context
        type: string
      responses:
        '400':
          description: '`InvalidContextTypeException` - Indicates the slot context
            type is not one of "global", "category", or "folder"'
        '204':
          description: ''
        '404':
          description: '`ABTestNotFoundException` - Indicates that the abTest with
            the given abTest ID is not found. or `SlotWithContextTypeNotFoundException`
            - Indicates that the slot with the given slot ID and context type is not
            found. or `SlotConfigurationIdentifierNotFoundException` - Indicates that
            the slot with the given slot ID, slot configuration ID and context type
            is not found. or `ABTestSegmentNotFoundException` - thrown when the segment
            with the given id is not found. or `SiteNotFoundException` - thrown when
            the site with the given id is not found.'
      security:
      - oauth2_application: []
      tags:
      - sites
