swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  coupon_system_code_config:
    properties:
      code_prefix:
        description: The code prefix for system-generated coupon codes.
        x-label:
          default: Code Prefix
        type: string
      number_of_codes:
        description: The number of system coupon codes that can be issued.
        format: int32
        type: integer
  coupon:
    description: Document representing a coupon.
    properties:
      case_insensitive:
        description: "True if a coupon is case insensitive; false otherwise. This\
          \ attribute on the coupon can not be\n modified after the coupon has been\
          \ created. If an attempt was made to modify this the system would return\n\
          \ CouponUpdateForbiddenException"
        type: boolean
      coupon_id:
        description: The id of the coupon.
        x-label:
          default: ID
        maxLength: 256
        minLength: 1
        readOnly: true
        type: string
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      description:
        description: The description of the coupon.
        maxLength: 4000
        type: string
      enabled:
        description: A flag indicating whether the coupon is enabled.
        x-label:
          default: Enabled
        type: boolean
      exported_code_count:
        description: The number of coupon codes attached to the coupon that have been
          issued (request search only).
        format: int32
        type: integer
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: A link to the coupon.
        type: string
      multiple_codes_per_basket:
        description: "True if a coupon with multiple codes can have different codes\
          \ used on the same basket or order. If the coupon\n type does not support\
          \ this configuration, this will return false."
        type: boolean
      redemption_count:
        description: The number of times the coupon has been redeemed (request search
          only).
        format: int32
        type: integer
      redemption_limits:
        $ref: '#/definitions/redemption_limits'
        description: The redemption limit per coupon code.
      single_code:
        description: Single coupon code, only valid for Single Code type
        maxLength: 256
        minLength: 1
        type: string
      system_codes_config:
        $ref: '#/definitions/coupon_system_code_config'
        description: The configuration of system coupon codes, including pre-fix and
          number of codes
      total_codes_count:
        description: The total number of coupon codes associated with this coupon
        format: int32
        type: integer
      type:
        description: The type of the coupon code.
        enum:
        - single_code
        - multiple_codes
        - system_codes
        x-enum-labels:
        - default: Coupon with multiple fixed codes
        - default: Coupon with single fixed code
        - default: Coupon with system generated codes
        x-label:
          default: Type
        readOnly: true
        type: string
  redemption_limits:
    description: Document representing a coupon.
    properties:
      limit_per_code:
        description: The redemption limit per code
        format: int32
        x-label:
          default: Redemptions per Code
        minimum: 0
        type: integer
      limit_per_customer:
        description: The redemption limit per customer
        format: int32
        x-label:
          default: Redemptions per Customer
        minimum: 0
        type: integer
      limit_per_time_frame:
        $ref: '#/definitions/redemption_limit_per_period'
        description: The redemption limit per time frame
        x-label:
          default: Redemptions per Timeframe
  redemption_limit_per_period:
    description: Document representing a coupon redemption limit.
    properties:
      limit:
        description: The limit on the number of times a coupon can be redeemed for
          a specified redemption time period.
        format: int32
        minimum: 0
        type: integer
      redemption_time_frame:
        description: The redemption time period.
        format: int32
        maximum: 999
        minimum: 0
        type: integer
paths:
  /sites/{site_id}/coupons/{coupon_id}:
    delete:
      description: Delete a coupon by id.
      operationId: deleteSitesByIDCouponsByID
      parameters:
      - description: The site context.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: Id of the coupon to delete from the site.
        in: path
        minLength: 1
        name: coupon_id
        required: true
        type: string
      responses:
        '204':
          description: ''
      security:
      - oauth2_application: []
      tags:
      - sites
    get:
      description: "Action to get coupon information.\n\n The following fields are\
        \ returned in the Coupon document when specifying the *stats* expand:\n \n\
        \     - exported_code_count\n     - redemption_count\n     - total_codes_count\n\
        \ \n \n\n If the role to which the user belongs does not have View_Coupon_Codes\
        \ permission, then the coupon codes returned will be masked."
      operationId: getSitesByIDCouponsByID
      parameters:
      - description: The site context.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The id of the requested coupon.
        in: path
        minLength: 1
        name: coupon_id
        required: true
        type: string
      - description: The property selector.
        in: query
        name: select
        type: string
      - description: The expand parameter. A comma separated list with the allowed
          values (*stats*).
        in: query
        items:
          type: string
        name: expand
        type: array
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/coupon'
        '404':
          description: '`CouponNotFoundException` - Thrown in case the coupon does
            not exist matching the given id'
      security:
      - oauth2_application: []
      tags:
      - sites
    patch:
      description: Updates the coupon with the specified information.
      operationId: patchSitesByIDCouponsByID
      parameters:
      - description: The site context.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The id of the requested coupon.
        in: path
        minLength: 1
        name: coupon_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/coupon'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/coupon'
        '400':
          description: "`CouponUpdateReadOnlyException` - Thrown if you try to update\
            \ certain fields in a coupon after\n              redeeming or exporting\
            \ it. or `CouponCodeDuplicateException` - Thrown if the code provided\
            \ is in use by another coupon. or `SystemGeneratedCouponQuotaException`\
            \ - Thrown whenever a quota regarding system-generated coupons is violated"
        '403':
          description: '`CouponUpdateForbiddenException` - Thrown when trying to update
            a broken coupon, that should be deleted and re-created. or `CouponLegacyUpdateForbiddenException`
            - Thrown when trying to update a legacy coupon.'
        '404':
          description: '`CouponNotFoundException` - Thrown if the coupon does not
            exist matching the given id.'
      security:
      - oauth2_application: []
      tags:
      - sites
    put:
      description: "Creates a coupon using the information provided. If a coupon exists\
        \ with the same unique identifier,\n the coupon is replaced completely."
      operationId: putSitesByIDCouponsByID
      parameters:
      - description: The site context.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The id of the coupon to create.
        in: path
        minLength: 1
        name: coupon_id
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/coupon'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/coupon'
        '400':
          description: "`CouponInvalidException` - Thrown if the coupon passed in\
            \ is not valid (the argument indicates\n              the field that was\
            \ invalid). or `CouponCodeDuplicateException` - Thrown if the code provided\
            \ is in use by another coupon. or `CouponCreateSingleCodeException` -\
            \ Thrown if a single code coupon does not set the coupon code properly.\
            \ or `IdConflictException` - if the Id in request is not the same as the\
            \ ID in document. or `SystemGeneratedCouponQuotaException` - Thrown whenever\
            \ a quota regarding system-generated coupons is violated"
        '403':
          description: '`SiteAccessForbiddenException` - Thrown if the resource requires
            global instead of site-specific context.'
      security:
      - oauth2_application: []
      tags:
      - sites
