swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  recurrence:
    description: Document representing a schedule recurrence.
    properties:
      day_of_week:
        description: The days of week for recurrence.
        enum:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
        items:
          enum:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
          type: string
        type: array
      time_of_day:
        $ref: '#/definitions/time_of_day'
        description: The time of the day for recurrence.
  markup_text:
    properties:
      markup:
        description: The rendered HTML (read only)
        type: string
      source:
        description: "The raw markup text\n (only this needs to be provided in update\
          \ request)"
        type: string
  promotion_campaign_assignment:
    description: Document representing a promotion campaign assignment.
    properties:
      campaign:
        $ref: '#/definitions/campaign'
        description: The campaign
      campaign_id:
        description: The id of the campaign.
        maxLength: 256
        minLength: 1
        type: string
      coupons:
        description: The sorted array of assigned coupon ids.
        items:
          type: string
        type: array
      coupons_based:
        description: "True if the assigned promotion is coupon based. When set to\
          \ false, Coupons in the campaign and on the\n PromotionCampaignAssignment\
          \ are ignored. The default value is true."
        type: boolean
      creation_date:
        format: date-time
        type: string
      customer_groups:
        description: The sorted array of assigned customer groups.
        items:
          type: string
        type: array
      customer_groups_based:
        description: "True if the assigned promotion is customer group based. When\
          \ set to false, Customer Groups in the campaign and on\n the PromotionCampaignAssignment\
          \ are ignored. The default value is true."
        type: boolean
      description:
        description: The description of the promotion campaign assignment.
        maxLength: 4000
        type: string
      enabled:
        description: True if the assignment resource is enabled
        type: boolean
      last_modified:
        format: date-time
        type: string
      link:
        description: link for convenience
        type: string
      promotion:
        $ref: '#/definitions/promotion'
        description: The promotion
      promotion_id:
        description: The id of the Promotion.
        maxLength: 256
        minLength: 1
        type: string
      rank:
        description: The rank of promotion campaign assignment
        format: int32
        type: integer
      required_qualifier:
        description: "A constant indicating that one or all qualifier conditions must\
          \ be\n met in order for the promotion to apply for a given customer.\n Valid\
          \ values are \"any\" and \"all\"."
        enum:
        - any
        - all
        type: string
      schedule:
        $ref: '#/definitions/schedule'
        description: The schedule of the assignment resource
      source_code_based:
        description: "True if the assigned promotion is source code group based. When\
          \ set to false, Source Code Groups in the campaign and on\n the PromotionCampaignAssignment\
          \ are ignored. The default value is true."
        type: boolean
      source_code_groups:
        description: The sorted array of assigned source code groups.
        items:
          type: string
        type: array
  promotions:
    description: A set of promotions
    properties:
      count:
        format: int32
        type: integer
      data:
        description: The set of promotions
        items:
          $ref: '#/definitions/promotion'
        type: array
      expand:
        items:
          type: string
        type: array
      next:
        type: string
      previous:
        type: string
      select:
        type: string
      start:
        format: int32
        minimum: 0
        type: integer
      total:
        format: int32
        type: integer
  promotion_assignment_information:
    properties:
      abtest_id:
        description: "If there is only one assignment, and that assignment is an A/B\
          \ test segment, the id of the A/B test the segment\n belongs to. Otherwise,\
          \ empty."
        type: string
      abtest_segment_id:
        description: "If there is only one assignment, and that assignment is an A/B\
          \ test segment, the id of the A/B test segment.\n Otherwise, empty."
        type: string
      active:
        description: true if the individual assignment or the multiple assignments
          are currently active.
        type: boolean
      active_abtest_assignments:
        description: A list of currently active A/B tests this is assigned to.
        items:
          $ref: '#/definitions/promotion_abtest_group_assignment'
        type: array
      active_campaign_assignments:
        description: A list of currently active campaigns this is assigned to.
        items:
          $ref: '#/definitions/promotion_campaign_assignment'
        type: array
      campaign_id:
        description: If there is only one assignment, and that assignment is a campaign,
          the id of the campaign. Otherwise, empty.
        type: string
      enabled:
        type: boolean
      end_date:
        description: "The end date of the container of the assignment (a Campaign\
          \ or ABTest). If schedule_type is\n schedule_type : \"multiple\" or schedule_type\
          \ : \"none\", then then result will be null. Also, a null\n date will also\
          \ return null."
        format: date-time
        type: string
      schedule:
        $ref: '#/definitions/schedule'
        description: "The schedule of the assignment (a Campaign or ABTest). If schedule_type\
          \ is\n schedule_type : \"multiple\" or schedule_type : \"none\", then then\
          \ result will be null."
      schedule_type:
        description: "If there is only one active assignment, or no active assignments\
          \ and one upcoming assignment, this is that type\n of assignment (schedule_type\
          \ : \"campaign\" or schedule_type : \"abtest\"). If there are no\n assignments,\
          \ it will be schedule_type : \"none\", otherwise, schedule_type : \"multiple\"\
          ."
        enum:
        - none
        - campaign
        - abtest
        - multiple
        type: string
      start_date:
        description: "The start date of the container of the assignment (a Campaign\
          \ or ABTest). If schedule_type is\n schedule_type : \"multiple\" or schedule_type\
          \ : \"none\", then then result will be null. Also, a null\n date will also\
          \ return null."
        format: date-time
        type: string
      upcoming_abtest_assignments:
        description: A list of upcoming A/B tests this is assigned to.
        items:
          $ref: '#/definitions/promotion_abtest_group_assignment'
        type: array
      upcoming_campaign_assignments:
        description: A list of upcoming campaigns this is assigned to.
        items:
          $ref: '#/definitions/promotion_campaign_assignment'
        type: array
  promotion_abtest_group_assignment:
    properties:
      abtest_description:
        type: string
      abtest_id:
        type: string
      enabled:
        type: boolean
      schedule:
        $ref: '#/definitions/schedule'
      segment_description:
        type: string
      segment_id:
        type: string
  campaign:
    description: Document representing a campaign.
    properties:
      campaign_id:
        description: The ID of the campaign.
        x-label:
          default: ID
        maxLength: 256
        minLength: 1
        type: string
      coupons:
        description: The array of assigned coupon IDs, not sorted
        items:
          type: string
        type: array
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      customer_groups:
        description: The array of assigned customer groups, not sorted
        items:
          type: string
        type: array
      description:
        description: The description of the campaign.
        format: text
        x-label:
          default: Description
        maxLength: 4000
        type: string
      enabled:
        description: The enabled flag for campaign.
        type: boolean
      end_date:
        description: The date that the Scenario ends
        format: date-time
        x-label:
          default: End Date
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: link for convenience
        type: string
      source_code_groups:
        description: The array of assigned source code groups, not sorted
        items:
          type: string
        type: array
      start_date:
        description: The date that the Scenario begins
        format: date-time
        x-label:
          default: Start Date
        type: string
  promotion:
    description: "Document representing a promotion. Unless otherwise stated, attributes\
      \ of this document are not supported when using\n the Open Commerce API to update\
      \ multiple promotions at once."
    properties:
      archived:
        description: "Determines whether or not this promotion is archived. This attribute\
          \ is allowed to be updated when using the Open\n Commerce API to update\
          \ multiple promotions at once."
        type: boolean
      assignment_information:
        $ref: '#/definitions/promotion_assignment_information'
        description: Information about the assignments and assignment schedules of
          this promotion
      callout_msg:
        additionalProperties:
          $ref: '#/definitions/markup_text'
        description: The localized callout message of the promotion.
        format: localized
        x-label:
          default: Callout Message
        type: object
      creation_date:
        description: Returns the value of attribute 'creationDate'.
        format: date-time
        x-label:
          default: Creation Date
        readOnly: true
        type: string
      currency_code:
        description: "The ISO 4217 mnemonic code of the currency this promotion is\
          \ restricted to. If not populated, then there is no\n currency restriction\
          \ on the promotion."
        maxLength: 3
        type: string
      disable_globally_excluded:
        description: Determines whether or not this promotion ignores the global product
          exclusions for promotions.
        type: boolean
      enabled:
        description: "Determines whether or not this promotion is enabled. This attribute\
          \ is allowed to be updated when using the Open\n Commerce API to update\
          \ multiple promotions at once."
        type: boolean
      exclusivity:
        description: "Determines if the promotion can be combined with other promotions\
          \ of the same promotion class or if it cannot be\n combined with any other\
          \ promotions. This attribute is allowed to be updated when using the Open\
          \ Commerce API to\n update multiple promotions at once."
        enum:
        - 'no'
        - class
        - global
        x-enum-labels:
        - default: Can't be combined with promotions of the same class.
        - default: Can't be combined with any promotion.
        - default: Can be combined with any promotion.
        x-label:
          default: Exclusivity
        type: string
      id:
        description: The id for the promotion.
        x-label:
          default: ID
        type: string
      last_modified:
        description: Returns the value of attribute 'lastModified'.
        format: date-time
        x-label:
          default: Last Modified
        readOnly: true
        type: string
      link:
        description: A URL that is used to get the details of this promotion.
        type: string
      name:
        additionalProperties:
          type: string
        description: The user supplied name of this promotion, which can be localized
        format: localized
        x-label:
          default: Name
        type: object
      promotion_class:
        description: "The class of the promotion. If the promotion class is modified,\
          \ then the promotion rule and all of its values,\n such as whether or not\
          \ to disable global product exclusions, will be reset."
        enum:
        - product
        - shipping
        - order
        type: string
      tags:
        description: "Returns the list of tags assigned to this promotion. If used\
          \ to set the tags on a promotion, the promotion will\n only have the tags\
          \ passed in the input. Any existing tags will be removed."
        items:
          $ref: '#/definitions/tag'
        x-label:
          default: Tags
        type: array
  schedule:
    description: Document representing a time schedule for slots.
    properties:
      end_date:
        description: 'The date to end of validity. ISO8601 date time format: yyyy-MM-dd''T''HH:mm:ssZ.'
        format: date-time
        type: string
      recurrence:
        $ref: '#/definitions/recurrence'
        description: The recurrence of the schedule by day of week and time of day.
          Not all schedules will support a recurrence.
      start_date:
        description: 'The date to start validity. ISO8601 date time format: yyyy-MM-dd''T''HH:mm:ssZ.'
        format: date-time
        type: string
  tag:
    description: Document representing a tag
    properties:
      tag_id:
        description: The id of the tag.
        type: string
  time_of_day:
    description: Document representing a time schedule within a single day.
    properties:
      time_from:
        description: "The time to start from. Time format: HH:mm:ss. Seconds\n are\
          \ ignored and set to 0."
        format: time
        type: string
      time_to:
        description: "The time to end on. Time format: HH:mm:ss. Seconds\n are ignored\
          \ and set to 0."
        format: time
        type: string
paths:
  /sites/{site_id}/coupons/{coupon_id}/campaigns/{campaign_id}/promotions:
    get:
      description: Get the promotions for a campaign that have a coupon assigned to
        them either directly or through campaigns.
      operationId: getSitesByIDCouponsByIDCampaignsByIDPromotions
      parameters:
      - description: The site context.
        in: path
        minLength: 1
        name: site_id
        required: true
        type: string
      - description: The id of the coupon that is assigned to promotions directly
          or through campaigns.
        in: path
        name: coupon_id
        required: true
        type: string
      - description: The id of the campaign that we want to restrict the set of promotions
          for.
        in: path
        name: campaign_id
        required: true
        type: string
      - description: Optional start index for retrieving the promotions (default 0).
        format: int32
        in: query
        name: start
        type: integer
      - description: Optional count for retrieving the promotions (default is 25).
        format: int32
        in: query
        name: count
        type: integer
      - description: ''
        in: query
        name: select
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/promotions'
        '404':
          description: '`CouponNotFoundException` - Thrown if the coupon does not
            exist matching the given id. or `CampaignNotFoundException` - Thrown if
            the campaign does not exist matching the given id.'
      security:
      - oauth2_application: []
      tags:
      - sites
