swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  object_type_definitions:
    description: Document representing an unfiltered list of system object types.
    properties:
      count:
        description: The number of returned documents.
        format: int32
        type: integer
      data:
        description: ''
        items:
          $ref: '#/definitions/object_type_definition'
        type: array
      expand:
        description: The list of expands set for the search request. Expands are optional.
        items:
          type: string
        type: array
      next:
        description: The URL of the next result page.
        type: string
      previous:
        description: The URL of the previous result page.
        type: string
      select:
        description: The fields that you want to select.
        type: string
      start:
        description: The zero-based index of the first search hit to include in the
          result.
        format: int32
        minimum: 0
        type: integer
      total:
        description: The total number of documents.
        format: int32
        type: integer
  object_type_definition:
    description: Document representing a object type definition
    properties:
      attribute_definition_count:
        description: Returns the number of attribute definitions contained by the
          type.  This is a computed attribute and cannot be changed.
        format: int32
        type: integer
      attribute_group_count:
        description: Returns the number of attribute groups contained by the type.  This
          is a computed attribute and cannot be changed.
        format: int32
        type: integer
      content_object:
        description: True if the object type definition is marked as a content object
        type: boolean
      creation_date:
        format: date-time
        type: string
      description:
        additionalProperties:
          type: string
        description: The user entered description for the type (localizable)
        format: localized
        type: object
      display_name:
        additionalProperties:
          type: string
        description: The user entered display name (localizable)
        format: localized
        type: object
      last_modified:
        format: date-time
        type: string
      link:
        description: URL that is used to get this instance.  This is a computed attribute
          and cannot be changed.
        type: string
      object_type:
        description: The object type identifier
        type: string
      queryable:
        description: True if the system object type is queryable, false otherwise.  Default
          is true.
        type: boolean
      read_only:
        description: True if the system object is read-only, false otherwise.  This
          is a computed attribute and cannot be changed.
        type: boolean
paths:
  /system_object_definitions:
    get:
      description: Action to get all the system objects with no filtering.
      operationId: getSystemObjectDefinitions
      parameters:
      - description: Optional start index for retrieving the items from a given index
          (default 0).
        format: int32
        in: query
        name: start
        type: integer
      - description: Optional count for retrieving only a subset of the items (default
          is 25).
        format: int32
        in: query
        name: count
        type: integer
      - description: The property selector.
        in: query
        name: select
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/object_type_definitions'
      security:
      - oauth2_application: []
      tags:
      - system_object_definitions
