swagger: '2.0'
host: abcd-001.dx.commercecloud.salesforce.com
info:
  description: 'Data API endpoints enable developers to build applications for merchants:
    Create, update, delete business objects, like products, customers, pricing and
    promotions or assignments. They typically provide read and write access and are
    designed for moderate usage.'
  title: Data API
  version: '24.1'
basePath: /s/-/dw/data/v24.1
consumes:
- application/json
- text/xml
- application/xml
produces:
- application/json
- text/xml
- application/xml
securityDefinitions:
  oauth2_application:
    description: Authentication flow with client ID and password with account manager.
    flow: application
    tokenUrl: https://account.demandware.com:443/dw/oauth2/access_token
    type: oauth2
  client_id:
    description: Add client ID for application identification. Alternative as 'client_id'
      query parameter.
    in: header
    name: x-dw-client-id
    type: apiKey
definitions:
  object_type_definition:
    description: Document representing a object type definition
    properties:
      attribute_definition_count:
        description: Returns the number of attribute definitions contained by the
          type.  This is a computed attribute and cannot be changed.
        format: int32
        type: integer
      attribute_group_count:
        description: Returns the number of attribute groups contained by the type.  This
          is a computed attribute and cannot be changed.
        format: int32
        type: integer
      content_object:
        description: True if the object type definition is marked as a content object
        type: boolean
      creation_date:
        format: date-time
        type: string
      description:
        additionalProperties:
          type: string
        description: The user entered description for the type (localizable)
        format: localized
        type: object
      display_name:
        additionalProperties:
          type: string
        description: The user entered display name (localizable)
        format: localized
        type: object
      last_modified:
        format: date-time
        type: string
      link:
        description: URL that is used to get this instance.  This is a computed attribute
          and cannot be changed.
        type: string
      object_type:
        description: The object type identifier
        type: string
      queryable:
        description: True if the system object type is queryable, false otherwise.  Default
          is true.
        type: boolean
      read_only:
        description: True if the system object is read-only, false otherwise.  This
          is a computed attribute and cannot be changed.
        type: boolean
paths:
  /system_object_definitions/{object_type}:
    get:
      description: Action to get system object information.
      operationId: getSystemObjectDefinitionsByID
      parameters:
      - description: The id of the object type for the requested system object.
        in: path
        minLength: 1
        name: object_type
        required: true
        type: string
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/object_type_definition'
        '404':
          description: '`SystemObjectNotFoundException` - Thrown in case the system
            object does not exist matching the given objectType'
      security:
      - oauth2_application: []
      tags:
      - system_object_definitions
